- name: installing nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: enabel and starting nginx
  ansible.builtin.service:
    name: nginx
    enabled: yes
    state: started

- name: include from common roles
  include_role:
    name: common
    tasks_from: main

- name: copy expense configuration
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify:
  - Restart Nginx